### ISSUE TITLE
possible venue location

### ISSUE THREAD

**Issue by saifikhan** [rustox/rep#5]
who do we communicate with to explore the possiblity of providing a hosting venue for 3 hrs on a saturday afternoon once a month ?

**Comment by raginijx** [comment]
These days Bangalore co-working spaces are very active in conducting open events.
Since ours is a community event and we can discuss with them.

**Comment by saifikhan** [comment]
is there a co-working space that you have in mind ?

**Comment by saifikhan** [comment]
is it a good idea to check with the GoJek folks at Diamond district ?

**Comment by raginijx** [comment]
Co-working space: 91springboard

**Comment by saifikhan** [comment]
What is th status update on this ?

**Comment by raginijx** [comment]
I sent an email to Siddartha of 91Springboard sending him all the details about the community.

We also had a meeting on 1st May.
Minutes of meeting:
 * They are fine with conducting the event at 91Springboard.
 * Any changes, they will inform one week before.
 * If the number of attendees is 20 then we can conduct it in the conference room otherwise they have event room where they conduct most of their events.

**Comment by raginijx** [comment]
https://groups.google.com/forum/#!msg/rustox/4YbjpbAfsIM/479L0xs3BgAJ

Venue has been confirmed by the sponsors.
